# Generated by Django 4.0 on 2023-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('confpass', models.CharField(max_length=15)),
            ],
        ),
    ]
