# Generated by Django 4.0 on 2023-02-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
