# Generated by Django 4.0 on 2023-02-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('CP', 'Cell Phones'), ('AP', 'Appliances'), ('PT', 'Computer Parts'), ('FN', 'Furniture')], max_length=50),
        ),
    ]
