# Generated by Django 4.0 on 2023-03-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_products_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[("{'CP': 'Cell Phones'}", 'Cell Phones'), ("{'AP': 'Appliances'}", 'Appliances'), ("{'PT': 'Computer Parts'}", 'Comp Parts'), ("{'FN': 'Furniture'}", 'Furniture')], max_length=50),
        ),
    ]
