# Generated by Django 4.0 on 2023-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0010_products_status_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default='Available'),
        ),
    ]
