# Generated by Django 4.0 on 2023-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_alter_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status: Innactive / Active')),
                ('trading_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status: Out of Stock / Available'),
        ),
    ]
