# Generated by Django 4.0 on 2023-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0016_alter_entry_notes_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_notes',
            name='supplier',
            field=models.CharField(choices=[("<QuerySet [{'company_name': 'Pharmassia du Seu Creysson'}, {'company_name': 'Quitanda Potato'}, {'company_name': 'Pesqueiro do Pato'}, {'company_name': 'kakakaka'}]>", 'Choices')], max_length=500),
        ),
    ]
