# Generated by Django 4.0 on 2023-05-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0017_alter_entry_notes_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_notes',
            name='supplier',
            field=models.CharField(default=({'company_name': 'Pharmassia du Seu Creysson'}, {'company_name': 'Quitanda Potato'}, {'company_name': 'Pesqueiro do Pato'}, {'company_name': 'kakakaka'}), max_length=500),
        ),
    ]
